import math

hh101_location={
    'D001': (10,5),
    'D002': (20,1),
    #'D003': (28,6),
    # 'LS001': (22,2),
    # 'LS002': (4,4),
    # 'LS003': (4,9),
    # 'LS004': (4,14),
    # 'LS005': (15,11),
    # 'LS006': (6,2),
    # 'LS007': (6,4),
    # 'LS008': (13,19),
    # 'LS009': (26,15),
    # 'LS010': (19,5),
    # 'LS011': (26,9),
    # 'LS012': (31,19),
    # 'LS013': (21,13),
    # 'LS014': (29,10),
    # 'LS015': (29,8),
    # 'LS016': (5,11),
    'M001': (22,2),
    'M002': (4,4),
    'M003': (4,9),
    'M004': (4,14),
    'M005': (15,11),
    'M006': (6,2),
    'M007': (6,4),
    'M008': (13,19),
    'M009': (26,15),
    'M010': (19,5),
    'M011': (26,9),
    'M012': (31,19),
    'MA013': (21,13),
    'MA014': (29,10),
    'MA015': (29,8),
    'MA016': (5,11),
    # 'T101': (10,5),
    # 'T102': (20,1),
    # 'T103': (28,6),
    # 'T104': (10,6),
    # 'T105': (10,6),
}

baseline_activities={
    '':                         'Other',
    'Bathe':                    'Bathe',
    'Bed_Toilet_Transition':    'Bed_Toilet_Transition',
    'Cook':                     'Cook',
    'Cook_Breakfast':           'Cook',
    'Cook_Dinner':              'Cook',
    'Cook_Lunch':               'Cook',
    'Dress':                    'Other',
    'Eat':                      'Eat',
    'Eat_Breakfast':            'Eat',
    'Eat_Dinner':               'Eat',
    'Eat_Lunch':                'Eat',
    'Enter_Home':               'Enter_Home',
    'Entertain_Guests':         'Other',
    'Evening_Meds':             'Other',
    'Groom':                    'Other',
    'Leave_Home':               'Leave_Home',
    'Morning_Meds':             'Other',
    'Personal_Hygiene':         'Personal_Hygiene',
    'Phone':                    'Other',
    'Read':                     'Other',
    'Relax':                    'Relax',
    'Sleep':                    'Sleep',
    'Sleep_Out_Of_Bed':         'Sleep',
    'Toilet':                   'Other',
    'Wash_Breakfast_Dishes':    'Wash_Dishes',
    'Wash_Dinner_Dishes':       'Wash_Dishes',
    'Wash_Dishes':              'Wash_Dishes',
    'Wash_Lunch_Dishes':        'Wash_Dishes',
    'Watch_TV':                 'Other',
    'Work_At_Table':            'Work'
}

# act_rulsif={
#     '':                         'Other',
#     'Bathe':                    'Bathing',
#     'Bed_Toilet_Transition':    'Bed_Toilet_Transition',
#     'Cook':                     'Cook',
#     'Cook_Breakfast':           'Cook',
#     'Cook_Dinner':              'Cook',
#     'Cook_Lunch':               'Cook',
#     'Dress':                    'Other',
#     'Eat':                      'Eating',
#     'Eat_Breakfast':            'Eating',
#     'Eat_Dinner':               'Eating',
#     'Eat_Lunch':                'Eating',
#     'Enter_Home':               'Enter_Home',
#     'Entertain_Guests':         'Other',
#     'Evening_Meds':             'Take_Medicine',
#     'Groom':                    'Other',
#     'Leave_Home':               'Leave_Home',
#     'Morning_Meds':             'Take_Medicine',
#     'Personal_Hygiene':         'Personal_Hygiene',
#     'Phone':                    'Other',
#     'Read':                     'Other',
#     'Relax':                    'Relax',
#     'Sleep':                    'Sleep',
#     'Sleep_Out_Of_Bed':         'Sleep',
#     'Toilet':                   'Other',
#     'Wash_Breakfast_Dishes':    'Wash_Dishes',
#     'Wash_Dinner_Dishes':       'Wash_Dishes',
#     'Wash_Dishes':              'Wash_Dishes',
#     'Wash_Lunch_Dishes':        'Wash_Dishes',
#     'Watch_TV':                 'Other',
#     'Work_At_Table':            'Work'
# }