hh127_act={
    '':                         'X',
    'Bathe':                    'Bathe',
    'Bed_Toilet_Transition':    'Bed_Toilet_Transition',
    'Cook':                     'Cook',
    'Cook_Breakfast':           'Cook',
    'Cook_Dinner':              'Cook',
    'Cook_Lunch':               'Cook',
    'Dress':                    'Other',
    'Drink':                    'Other',
    'Eat':                      'Eat',
    'Eat_Breakfast':            'Eat',
    'Eat_Dinner':               'Eat',
    'Eat_Lunch':                'Eat',
    'Enter_Home':               'Enter_Home',
    'Groom':                    'Other',
    'Leave_Home':               'Leave_Home',
    'Personal_Hygiene':         'Personal_Hygiene',
    'Phone':                    'Other',
    'Read':                     'Other',
    'Relax':                    'Relax',
    'Sleep':                    'Sleep',
    'Sleep_Out_Of_Bed':         'Sleep',
    'Step_Out':                 'Other',
    'Toilet':                   'Other',
    'Wash_Breakfast_Dishes':    'Wash_Dishes',
    'Wash_Dinner_Dishes':       'Wash_Dishes',
    'Wash_Dishes':              'Wash_Dishes',
    'Wash_Lunch_Dishes':        'Wash_Dishes',
    'Watch_TV':                 'Other',
    'Work_At_Table':            'Work'
}

hh127_sensor=[
    'D101',
    'M001',
    'M002',
    'M003',
    'M004',
    'M005',
    'M006',
    'M007',
    'M008',
    'M009',
    'M010',
    'M011',
    'M012',
    'M013',
    'M014',
    'M015',
    'T101',
    'T102',
    'T103',
    'T104',
    'T105',
]